// <auto-generated />
namespace webApp_codfirst_storeProsedure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class KitapTableColumnaciklama4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KitapTableColumnaciklama4));
        
        string IMigrationMetadata.Id
        {
            get { return "202212020754093_KitapTableColumnaciklama4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
